name: Run checks for html-converter
on:
  push:
    branches: [main] # run on pushes to master
    paths-ignore:
      - "!pacakges/**"
  pull_request:
    branches: [main] # run on pushes to master
    paths-ignore:
      - "!pacakges/**"
  pull_request_review:
    branches: [main] # run on pushes to master
    paths-ignore:
      - "!pacakges/**"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # setup the repository in the runner
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: yarn install --pure-lockfile
      - name: Eslint
        run: yarn eslint
      - name: Build Code
        run: yarn build
      - name: Test Code
        run: yarn test
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.7
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
          publish_command: "yarn"
          # publish_args: "--non-interactive"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
